// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class player_info;
@class player_info_Builder;
@class player_transform;
@class player_transform_Builder;

@interface TestRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface player_info : PBGeneratedMessage {
@private
  BOOL hasId_:1;
  BOOL hasName_:1;
  BOOL hasEmail_:1;
  int32_t id;
  NSString* name;
  NSString* email;
}
- (BOOL) hasName;
- (BOOL) hasId;
- (BOOL) hasEmail;
@property (readonly, retain) NSString* name;
@property (readonly) int32_t id;
@property (readonly, retain) NSString* email;

+ (player_info*) defaultInstance;
- (player_info*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (player_info_Builder*) builder;
+ (player_info_Builder*) builder;
+ (player_info_Builder*) builderWithPrototype:(player_info*) prototype;

+ (player_info*) parseFromData:(NSData*) data;
+ (player_info*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (player_info*) parseFromInputStream:(NSInputStream*) input;
+ (player_info*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (player_info*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (player_info*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface player_info_Builder : PBGeneratedMessageBuilder {
@private
  player_info* result;
}

- (player_info*) defaultInstance;

- (player_info_Builder*) clear;
- (player_info_Builder*) clone;

- (player_info*) build;
- (player_info*) buildPartial;

- (player_info_Builder*) mergeFrom:(player_info*) other;
- (player_info_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (player_info_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasName;
- (NSString*) name;
- (player_info_Builder*) setName:(NSString*) value;
- (player_info_Builder*) clearName;

- (BOOL) hasId;
- (int32_t) id;
- (player_info_Builder*) setId:(int32_t) value;
- (player_info_Builder*) clearId;

- (BOOL) hasEmail;
- (NSString*) email;
- (player_info_Builder*) setEmail:(NSString*) value;
- (player_info_Builder*) clearEmail;
@end

@interface player_transform : PBGeneratedMessage {
@private
  BOOL hasPosX_:1;
  BOOL hasPosY_:1;
  BOOL hasPosZ_:1;
  BOOL hasRotX_:1;
  BOOL hasRotY_:1;
  BOOL hasRotZ_:1;
  BOOL hasName_:1;
  int32_t posX;
  int32_t posY;
  int32_t posZ;
  int32_t rotX;
  int32_t rotY;
  int32_t rotZ;
  NSString* name;
}
- (BOOL) hasName;
- (BOOL) hasPosX;
- (BOOL) hasPosY;
- (BOOL) hasPosZ;
- (BOOL) hasRotX;
- (BOOL) hasRotY;
- (BOOL) hasRotZ;
@property (readonly, retain) NSString* name;
@property (readonly) int32_t posX;
@property (readonly) int32_t posY;
@property (readonly) int32_t posZ;
@property (readonly) int32_t rotX;
@property (readonly) int32_t rotY;
@property (readonly) int32_t rotZ;

+ (player_transform*) defaultInstance;
- (player_transform*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (player_transform_Builder*) builder;
+ (player_transform_Builder*) builder;
+ (player_transform_Builder*) builderWithPrototype:(player_transform*) prototype;

+ (player_transform*) parseFromData:(NSData*) data;
+ (player_transform*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (player_transform*) parseFromInputStream:(NSInputStream*) input;
+ (player_transform*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (player_transform*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (player_transform*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface player_transform_Builder : PBGeneratedMessageBuilder {
@private
  player_transform* result;
}

- (player_transform*) defaultInstance;

- (player_transform_Builder*) clear;
- (player_transform_Builder*) clone;

- (player_transform*) build;
- (player_transform*) buildPartial;

- (player_transform_Builder*) mergeFrom:(player_transform*) other;
- (player_transform_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (player_transform_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasName;
- (NSString*) name;
- (player_transform_Builder*) setName:(NSString*) value;
- (player_transform_Builder*) clearName;

- (BOOL) hasPosX;
- (int32_t) posX;
- (player_transform_Builder*) setPosX:(int32_t) value;
- (player_transform_Builder*) clearPosX;

- (BOOL) hasPosY;
- (int32_t) posY;
- (player_transform_Builder*) setPosY:(int32_t) value;
- (player_transform_Builder*) clearPosY;

- (BOOL) hasPosZ;
- (int32_t) posZ;
- (player_transform_Builder*) setPosZ:(int32_t) value;
- (player_transform_Builder*) clearPosZ;

- (BOOL) hasRotX;
- (int32_t) rotX;
- (player_transform_Builder*) setRotX:(int32_t) value;
- (player_transform_Builder*) clearRotX;

- (BOOL) hasRotY;
- (int32_t) rotY;
- (player_transform_Builder*) setRotY:(int32_t) value;
- (player_transform_Builder*) clearRotY;

- (BOOL) hasRotZ;
- (int32_t) rotZ;
- (player_transform_Builder*) setRotZ:(int32_t) value;
- (player_transform_Builder*) clearRotZ;
@end

